package client;
 

import java.util.Currency;
import com.master.client.bean.Client;
global org.slf4j.Logger log;


rule "check-transaction-type-for-null"
lock-on-active true
    when
        $C : Client(clientName==null)
    then
        System.out.println($C.toString());
        $C.getErrors().add("Client Id cannot be null ");
        System.out.println($C.toString());

        update ($C);
end


